#!/bin/bash
command -v brew && brew install yt-dlp sqlite3
command -v dnf && sudo dnf install yt-dlp sqlite3
command -v apt && sudo apt install yt-dlp sqlite3
pip install -U openai-whisper
curl -fsSL https://bun.sh/install | bash
